#!/bin/bash
set -e
set -o pipefail

if [ $(node -v | grep v8 | wc -l) != 1 ]; then
  echo >&2 "Error: node is not v8"
  exit 1
fi
yarn --offline || yarn || npm i
if [ -d src/index ]; then
  mv src/index .
fi
./gen-index
npm run build
./rm-index
mv index src/ 2>/dev/null || true
node ./mk-package.js > dist/package.json
echo "done."
